name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up GCP Credentials
      - name: Set up GCP Credentials
        run: echo "${{ secrets.GCLOUD_KEY_FILE }}" > key.json

      # Authenticate with GCP
      - name: Authenticate GCP
        run: |
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project alpine-furnace-237115

      # Deploy Application
      - name: Deploy to GCP VM
        run: |
          gcloud compute ssh fausto@34.42.230.190 --command "
          cd derive-tech-app &&
          git pull &&
          pm2 restart all"
