name: CI/CD Deployment to GCP VM

on:
  push:
    branches:
      - master # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure the full commit history is fetched

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Provide SSH Passphrase
        run: |
          echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add -
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

      - name: Verify SSH Agent
        run: ssh-add -l # Verifies the private key is loaded correctly

      - name: Deploy Application to VM
        run: |
          ssh -o StrictHostKeyChecking=no username@your-vm-ip << EOF
          set -e  # Exit immediately if a command exits with a non-zero status
          cd derive-tech-app  # Navigate to your project directory
          git pull origin main  # Pull the latest code from the repository
          npm install  # Install dependencies
          npm run build  # Build your application
          pm2 restart process_name  # Restart your application using PM2
          EOF
