name: Deploy to GCP VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Deploy to GCP VM
      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << 'EOF'
          # Navigate to the app directory
          cd derive-tech-app

          # Pull latest changes from Git
          git pull origin main

          # Install dependencies
          npm install

          # Build the app
          npm run build

          # Start or reload the app
          pm2 reload app || pm2 start npm --name "app" -- start
          EOF
    env:
      VM_IP: ${{ secrets.VM_IP }}
      VM_USER: ${{ secrets.VM_USER }}
