name: CI/CD Deployment to GCP VM

on:
  push:
    branches:
      - master # Triggdddderfdd the workflow on pushes #to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Google Cloud Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
          project_id: ${{ env.PROJECT_ID }}

      - name: Set Up Google Cloud CLI
        run: |
          curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-419.0.0-linux-x86_64.tar.gz
          tar -xvf google-cloud-cli-419.0.0-linux-x86_64.tar.gz
          ./google-cloud-sdk/install.sh
          ./google-cloud-sdk/bin/gcloud --version

      - name: Deploy Application
        run: |
          ./google-cloud-sdk/bin/gcloud compute ssh fausto@derive-web-staging --zone=us-central1-f --command "
          mkdir -p ~/.ssh
          echo '${{ secrets.SSH_PRIVATE_KEY }}' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          cd derive-tech-app
          git pull origin main || echo 'Failed to authenticate via SSH. Check your key configuration.'
          npm install
          npm run build
          pm2 start npm --name 'latest-derive' -- start
          "
